/**
 * Generates `testcase-generator/src/key_material.rs` with an obfuscated
 * XOR-split representation of the pool encryption key.
 *
 * The 32-byte key is split into 4 × 8-byte segments.
 * Each segment is XORed with a random 8-byte mask.
 * The Rust file exposes a `reconstruct_key()` function that reassembles
 * the key at runtime and returns a `Zeroizing<[u8; 32]>`.
 */
import { randomBytes } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

function toRustArray(buf: Buffer): string {
  return `[${Array.from(buf)
    .map((b) => `0x${b.toString(16).padStart(2, '0')}`)
    .join(', ')}]`
}

export function generateKeyMaterial(key: Buffer, projectRoot: string): void {
  if (key.length !== 32) {
    throw new Error(`Key must be 32 bytes, got ${key.length}`)
  }

  const segments: { data: Buffer; mask: Buffer }[] = []

  for (let i = 0; i < 4; i++) {
    const segment = key.subarray(i * 8, (i + 1) * 8)
    const mask = randomBytes(8)
    const xored = Buffer.alloc(8)
    for (let j = 0; j < 8; j++) {
      xored[j] = segment[j]! ^ mask[j]!
    }
    segments.push({ data: xored, mask })
  }

  const rust = `// Auto-generated by scripts/generate-key-material.ts — DO NOT EDIT
// This file is gitignored. Regenerate with: pnpm build:pools
use zeroize::Zeroizing;

const SEG0: [u8; 8] = ${toRustArray(segments[0]!.data)};
const MASK0: [u8; 8] = ${toRustArray(segments[0]!.mask)};

const SEG1: [u8; 8] = ${toRustArray(segments[1]!.data)};
const MASK1: [u8; 8] = ${toRustArray(segments[1]!.mask)};

const SEG2: [u8; 8] = ${toRustArray(segments[2]!.data)};
const MASK2: [u8; 8] = ${toRustArray(segments[2]!.mask)};

const SEG3: [u8; 8] = ${toRustArray(segments[3]!.data)};
const MASK3: [u8; 8] = ${toRustArray(segments[3]!.mask)};

/// Reconstruct the pool encryption key from obfuscated segments.
/// The returned value is wrapped in \`Zeroizing\` so it is zeroed on drop.
pub fn reconstruct_key() -> Zeroizing<[u8; 32]> {
    let mut key = Zeroizing::new([0u8; 32]);
    let pairs: [(&[u8; 8], &[u8; 8]); 4] = [
        (&SEG0, &MASK0),
        (&SEG1, &MASK1),
        (&SEG2, &MASK2),
        (&SEG3, &MASK3),
    ];
    for (i, (seg, mask)) in pairs.iter().enumerate() {
        for j in 0..8 {
            key[i * 8 + j] = seg[j] ^ mask[j];
        }
    }
    key
}
`

  const outPath = resolve(projectRoot, 'testcase-generator/src/key_material.rs')
  writeFileSync(outPath, rust, 'utf-8')
  console.log(`[key-material] Generated ${outPath}`)
}
