#!/usr/bin/env npx tsx
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  CHALLENGE_ID_PATTERN,
  compareChallengeId,
  extractFrontmatterId,
} from '../docs/shared/challenge-id.js'
// `_redirects` is a whitespace/newline-delimited format, so an unvalidated
// filename could break a rule line (space) or inject extra rules (newline).
// The slug contract is imported, not copied — a local literal is how a
// second (then third) incompatible slug rule drifts into existence.
import { SLUG_PATTERN } from '../docs/shared/challenge-slug.js'

// ── Pure helpers ──────────────────────────────────────────────────────────

export interface ChallengeFile {
  name: string
  content: string
}

/**
 * Build the Cloudflare Pages `_redirects` payload for the stable challenge
 * URLs: one `/c/<id> /challenge/<slug> 302` rule per challenge file.
 * Targets deliberately omit the `.html` extension so the rules keep working
 * under VitePress cleanUrls and plain static hosting alike.
 *
 * Lines are sorted by id so the output is reproducible regardless of
 * directory read order. Fails loudly (naming the offending file) on a
 * missing id line, a malformed id, or two files claiming the same id — a
 * silently skipped file would ship a catalogue with a dead stable URL.
 */
export function buildRedirects(files: ChallengeFile[]): string {
  // Zero challenges means the catalogue directory was moved or emptied — a
  // banner-only _redirects that silently kills every alias must never ship.
  if (files.length === 0) {
    throw new Error(
      '[generate-redirects] ERROR: no challenge markdown files found; refusing to write an empty redirects file.',
    )
  }
  const entries: { id: string; slug: string }[] = []
  const fileById = new Map<string, string>()

  for (const { name, content } of files) {
    // Scoped to the frontmatter block (not the whole file), so an `id:` line
    // in body text or a fenced code block can never be picked up.
    const id = extractFrontmatterId(content)
    if (id === null) {
      throw new Error(
        `[generate-redirects] ERROR: ${name} has no id line; fix the file before generating redirects.`,
      )
    }
    if (!CHALLENGE_ID_PATTERN.test(id)) {
      throw new Error(
        `[generate-redirects] ERROR: ${name} has id '${id}' which does not match the challenge id format (e.g. py001); fix the file before generating redirects.`,
      )
    }
    const claimedBy = fileById.get(id)
    if (claimedBy !== undefined) {
      throw new Error(
        `[generate-redirects] ERROR: duplicate id '${id}' claimed by both ${claimedBy} and ${name}; ids must be unique.`,
      )
    }
    fileById.set(id, name)
    const slug = name.replace(/\.md$/, '')
    if (!SLUG_PATTERN.test(slug)) {
      throw new Error(
        `[generate-redirects] ERROR: ${name} has a filename outside the slug contract [a-z0-9-]; a space or control character here would corrupt the _redirects line format.`,
      )
    }
    // An id-shaped slug no longer collides with the alias rules under /c/,
    // but it would still blur the catalogue identity: /challenge/py001 (a
    // slug) and /c/py001 (an alias) could then name two different challenges.
    if (CHALLENGE_ID_PATTERN.test(slug)) {
      throw new Error(
        `[generate-redirects] ERROR: ${name} has an id-shaped filename; an id-shaped slug would blur the catalogue identity (its /challenge/ page and the /c/ alias could name different challenges).`,
      )
    }
    entries.push({ id, slug })
  }

  entries.sort((a, b) => compareChallengeId(a.id, b.id))
  return entries.map(({ id, slug }) => `/c/${id} /challenge/${slug} 302\n`).join('')
}

/** Read every challenge markdown file under `dir` as {name, content} pairs. */
export function readChallengeFiles(dir: string): ChallengeFile[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => ({ name: f, content: readFileSync(join(dir, f), 'utf-8') }))
}

// ── Main (side-effects) ───────────────────────────────────────────────────

function main(): void {
  const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
  const files = readChallengeFiles(join(projectRoot, 'docs', 'challenge'))

  let output: string
  try {
    output = buildRedirects(files)
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err))
    process.exit(1)
  }

  const outDir = join(projectRoot, 'docs', 'public')
  mkdirSync(outDir, { recursive: true })
  // Banner lives in the write path only — buildRedirects stays a pure
  // rules-only payload for the unit tests. Cloudflare ignores lines it cannot
  // parse, so at worst the comment is dropped server-side.
  const banner =
    '# GENERATED by scripts/generate-redirects.ts — do not edit; regenerated on every pnpm dev/build\n'
  writeFileSync(join(outDir, '_redirects'), banner + output, 'utf-8')
  console.log(`[generate-redirects] Wrote ${files.length} redirects to docs/public/_redirects`)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main()
}
